version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes: 
      - ./packages:/home/ubuntu/packages
    ports:
      - "4000:4000"
    command: su ubuntu -c "cd /home/ubuntu/packages/backend && npm install && npm start"
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes: 
      - ./packages:/home/ubuntu/packages
    ports:
      - "3000:3000"
    command: su ubuntu -c "cd /home/ubuntu/packages/frontend && npm install && npm start"
